### ISSUE TITLE
Single File Selected not work

### ISSUE THREAD

**Issue by ismailyap** [robertlevonyan/media-picker#16] opened 2021-02-09 23:40 UTC
Single file selected gives 'Cannot access ... ' log , but if selected multi files its working perfect

**Comment by robertlevonyan** [comment] 2021-02-11 12:44
Fixed on version 2.0.1

**Comment by PaulaExposito** [comment] 2021-05-13 10:09
Hello, I am using 2.1.0 version and this bug is back. Only when selecting a single file.
![image](https://user-images.githubusercontent.com/56047765/118111009-08b19e80-b3db-11eb-816b-c325e914a47a.png)

**Comment by robertlevonyan** [comment] 2021-05-13 14:39
Do you have Storage Permission?

**Comment by PaulaExposito** [comment] 2021-05-13 15:18
Yes I do, with multiple files it works fine. I have downloaded the demo and the problem is there too.

**Comment by robertlevonyan** [comment] 2021-05-14 07:49
What is your Android version?

**Comment by PaulaExposito** [comment] 2021-05-14 09:07
I'm using 7.0 and 8.1.0

**Comment by robertlevonyan** [comment] 2021-05-20 11:00
Fixed. Please update to v.2.1.1.

**Closed by robertlevonyan** 2021-05-20 11:00 UTC
Labels: bug, fixed

**Comment by smad2** [comment] 2021-05-20 11:30
Can't reach the v.2.1.1 
![imagen](https://user-images.githubusercontent.com/32649036/118971300-8a6f7200-b96f-11eb-8d74-456bd5b3bc30.png)
